### ISSUE TITLE
Roadmap V1

### ISSUE THREAD

**Issue by DjDeveloperr** [js-play/feedback#1]
Here’s the stuff left to do for V1 i.e. initial launch of the app.

- [x] Change from Document based app to a user friendly UI for creating Playgrounds.
- [x] Add support for Objective-C reference types (for out-pointers).
- [ ] Support creating Objective-C classes in JS for implementing delegates and subclassing.
- [x] Support for passing JS callbacks as Obj C blocks.
- [x] Support for Structs.
- [x] Support for returning protocol based anonymous objects.
- [x] Redo Console Implementation to use different nodes for each log instead of a big string buffer. Also maybe add color support.
- [ ] Add support for File System APIs.
- [ ] Add support for Fetch API.
- [ ] Add support for HTTP and GitHub imports.
- [ ] Try exposing more Objective C frameworks.
- [ ] Widgets API for Home Screen and Lock Screen Widgets.
- [ ] ActivityKit support for Live Activities on Lock Screen and Dynamic Island.
- [ ] Shortcuts integration.
- [ ] Add documentation for our own APIs within app (not the bridged frameworks).
- [ ] Add a Premium/Pro purchase to unlock some features.
- [ ] Add many examples for Getting Started with the Runtime APIs.
